// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uaodddpzafmvhahunihm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhb2RkZHB6YWZtdmhhaHVuaWhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQzMDQ5OTgsImV4cCI6MjA4OTg4MDk5OH0.b2F32HcL8KOA-reCXlekfIwSLMpxRkOR0KVZ0qU1jAU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});